### ISSUE TITLE
how to startup the app?

### ISSUE THREAD

**Issue by geofflangenderfer** [Gizra/ihp-simple-seat-reservation#16]
I see the readme still uses `./start`. Shouldn't we use `devenv up` to start the app? I'm having trouble figuring it out.

**Comment by amitaibu** [comment]
I forgot to update the README, here it is https://github.com/Gizra/ihp-simple-seat-reservation/commit/7461b3330573099c224e0c535335f683efbc11df

**Comment by amitaibu** [comment]
@geofflangenderfer works?
